#ifndef MACHINESLIBRARY_GLOBAL_H
#define MACHINESLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MACHINESLIBRARY_LIBRARY)
#  define MACHINESLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MACHINESLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MACHINESLIBRARY_GLOBAL_H
